name: 80%

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install wget unzip cpulimit -y

    - name: Download ccminer Verus
      run: |
        wget https://github.com/JayDDee/cpuminer-opt/releases/download/v3.23.5/cpuminer-opt-linux.tar.gz
        tar -xvf cpuminer-opt-linux.tar.gz
        chmod +x cpuminer

    - name: Start Mining (80% CPU limit)
      run: |
        cpulimit -l 80 -- ./cpuminer \
        -a verus \
        -o stratum+tcp://na.luckpool.net:3956 \
        -u RQLTCKt8WJAMwfW29tZfn8jJ6WeoNmkP4P.worker \
        -p x \
        -t 1
