name: Verus Mining 80%

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install wget unzip build-essential automake autoconf libtool \
        pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev cpulimit -y

    - name: Download cpuminer source (zip)
      run: |
        wget https://codeload.github.com/JayDDee/cpuminer-opt/zip/refs/heads/master -O miner.zip
        unzip miner.zip
        mv cpuminer-opt-master cpuminer
        cd cpuminer
        ./build.sh

    - name: Start mining Verus (80% CPU)
      run: |
        cd cpuminer
        cpulimit -l 80 -- ./cpuminer \
        -a verus \
        -o stratum+tcp://na.luckpool.net:3956 \
        -u RQLTCKt8WJAMwfW29tZfn8jJ6WeoNmkP4P.worker \
        -p x \
        -t 1
